import { MigrationInterface, QueryRunner } from "typeorm";

export class Uzchess1786605018796 implements MigrationInterface {
    name = 'Uzchess1786605018796'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "userPermissions" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "userPermissions" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "userRoles" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "userRoles" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "rolePermissions" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "rolePermissions" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "refreshTokens" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "refreshTokens" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "refreshTokens" ALTER COLUMN "expiresAt" TYPE TIMESTAMP(0) USING "expiresAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "refreshTokens" ALTER COLUMN "revokedAt" TYPE TIMESTAMP(0) USING "revokedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseCategories" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseCategories" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "difficulty" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "difficulty" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "languages" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "languages" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "authors" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "authors" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseAuthors" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseAuthors" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseLessons" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseLessons" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseSections" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseSections" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "certificates" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "certificates" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseFavourites" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseFavourites" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "lessonProgresses" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "lessonProgresses" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "coursePurchases" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "coursePurchases" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseRatings" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "courseRatings" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "category" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "category" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "bookAuthors" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "bookAuthors" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "cart_items" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "cart_items" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "expiresAt" TYPE TIMESTAMP(0) USING "expiresAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "delivery_settings" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "delivery_settings" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "favourites" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "favourites" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "ratings" ALTER COLUMN "createdAt" TYPE TIMESTAMP(0) USING "createdAt"::timestamp(0)`);
        await queryRunner.query(`ALTER TABLE "ratings" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(0) USING "updatedAt"::timestamp(0)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ratings" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "ratings" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "favourites" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "favourites" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "delivery_settings" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "delivery_settings" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "expiresAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "expiresAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "coupons" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "cart_items" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "cart_items" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "bookAuthors" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "bookAuthors" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "books" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "category" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "category" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseRatings" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseRatings" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "coursePurchases" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "coursePurchases" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "lessonProgresses" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "lessonProgresses" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseFavourites" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseFavourites" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "certificates" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "certificates" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courses" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseSections" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseSections" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseLessons" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseLessons" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseAuthors" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseAuthors" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "authors" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "authors" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "languages" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "languages" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "difficulty" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "difficulty" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseCategories" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "courseCategories" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "refreshTokens" ALTER COLUMN "revokedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "revokedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "refreshTokens" ALTER COLUMN "expiresAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "expiresAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "refreshTokens" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "refreshTokens" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "rolePermissions" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "rolePermissions" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "userRoles" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "userRoles" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "userPermissions" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "updatedAt"::timestamptz(6)`);
        await queryRunner.query(`ALTER TABLE "userPermissions" ALTER COLUMN "createdAt" TYPE TIMESTAMP(6) WITH TIME ZONE USING "createdAt"::timestamptz(6)`);
    }

}
